// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVvwwxr9lzIt_4Wc4ISL7CSOJ_4xGNJI',
    appId: '1:838996762286:web:b26366ca86f722637d973f',
    messagingSenderId: '838996762286',
    projectId: 'fiteat-f1407',
    authDomain: 'fiteat-f1407.firebaseapp.com',
    storageBucket: 'fiteat-f1407.firebasestorage.app',
    measurementId: 'G-64ERMCDPTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCw8MN2KNLsTiXc620zr71lXtl37_Cx4',
    appId: '1:838996762286:android:ea3710f6f6d2e18d7d973f',
    messagingSenderId: '838996762286',
    projectId: 'fiteat-f1407',
    storageBucket: 'fiteat-f1407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lsbKow_ekMkm9y7kf99SwrhV4SirhK8',
    appId: '1:838996762286:ios:49d38bf501b199147d973f',
    messagingSenderId: '838996762286',
    projectId: 'fiteat-f1407',
    storageBucket: 'fiteat-f1407.firebasestorage.app',
    iosBundleId: 'com.example.fitEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5lsbKow_ekMkm9y7kf99SwrhV4SirhK8',
    appId: '1:838996762286:ios:49d38bf501b199147d973f',
    messagingSenderId: '838996762286',
    projectId: 'fiteat-f1407',
    storageBucket: 'fiteat-f1407.firebasestorage.app',
    iosBundleId: 'com.example.fitEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVvwwxr9lzIt_4Wc4ISL7CSOJ_4xGNJI',
    appId: '1:838996762286:web:d6f31318eae2c8377d973f',
    messagingSenderId: '838996762286',
    projectId: 'fiteat-f1407',
    authDomain: 'fiteat-f1407.firebaseapp.com',
    storageBucket: 'fiteat-f1407.firebasestorage.app',
    measurementId: 'G-YBF1FLWJYP',
  );
}
